let cannedAdapters = [
  {"id": "5a4f79aa-7c3a-4f23-afc2-27cef2bf14b8",
  "name": "MIT EECS Course Catalog",
  "url": "https://eecs.scripts.mit.edu/eduportal/who_is_teaching_what/F/2020/",
  "code": "{\n \"name\": \"MIT EECS Course Catalog\",\n \"urls\": [\n   \"https://eecs.scripts.mit.edu/eduportal/who_is_teaching_what/F/2020/\"\n ], \n \"matches\": [\n    \"https://eecs.scripts.mit.edu/eduportal/who_is_teaching_what/F/2020/\"\n ], \n \"attributes\": [\n   { \"name\": \"id\",\n     \"type\": \"text\",\n     \"hidden\": true\n   },\n   { \"name\": \"number\",\n     \"type\": \"text\"\n   },\n   { \"name\": \"title\",\n     \"type\": \"text\"\n   },\n   { \"name\": \"mode\",\n     \"type\": \"text\"\n   },\n   { \"name\": \"lecturers\",\n     \"type\": \"text\"\n   },\n   { \"name\": \"recitation instructors\",\n     \"type\": \"text\"\n   }\n  ],\n  \"scrapePage\": \"() => {return Array.from(document.querySelectorAll('tr[id]')).map(el => {let courseData = el.getElementsByTagName('td');let courseNumber = el.id;let courseName = courseData[0].innerText;  return {id: courseNumber, rowElements: [el], dataValues: { number: courseNumber, title: courseName.substring(courseNumber.length + 1), mode: courseData[1].innerText, lecturers: courseData[2].innerText, 'recitation instructors': courseData[3].innerText}  }})}   \",\n  \"onRowSelected\": \"(row) => { row.rowElements.forEach(el => { if (el.style) { el.style['background-color'] = '#c9ebff' } });  row.rowElements[0].scrollIntoView({ behavior: 'smooth', block: 'center' })}\",\n  \"onRowUnselected\": \"(row) => { row.rowElements.forEach(el => { if (el.style) { el.style['background-color'] = '' } });}\"   \n}",
  "description": "<h2>MIT EECS Course Catalog Info</h2><p>Description content</p>"
},
{"id": "68fed7c1-fd40-4fb7-9d8f-1c6f34a3f2cb",
  "name": "Hacker News",
  "url": "https://news.ycombinator.com/",
  "code": "{\n \"name\": \"Hacker News\",\n \"urls\": [\n   \"https://news.ycombinator.com/\"\n ], \n \"matches\": [\n    \"https://news.ycombinator.com/\"\n ], \n \"attributes\": [\n   { \"name\": \"id\",\n     \"type\": \"text\",\n     \"hidden\": true\n   },\n   { \"name\": \"rank\",\n     \"type\": \"numeric\"\n   },\n   { \"name\": \"title\",\n     \"type\": \"text\"\n   },\n   { \"name\": \"link\",\n     \"type\": \"text\"\n   },\n   { \"name\": \"points\",\n     \"type\": \"numeric\"\n   },\n   { \"name\": \"user\",\n     \"type\": \"text\"\n   }\n  ],\n  \"scrapePage\": \"() => {return Array.from(document.querySelectorAll('tr.athing')).map(el => { let detailsRow = el.nextElementSibling; let spacerRow = detailsRow.nextElementSibling; return { id: String(el.getAttribute('id')), rowElements: [el, detailsRow, spacerRow], dataValues: { rank: el.querySelector('span.rank'), title: el.querySelector('a.storylink'), link: el.querySelector('a.storylink').getAttribute('href'), points: detailsRow.querySelector('span.score'), user: detailsRow.querySelector('a.hnuser'),         }, }})}   \",\n  \"onRowSelected\": \"(row) => { row.rowElements.forEach(el => { if (el.style) { el.style['background-color'] = '#def3ff' } });  row.rowElements[0].scrollIntoView({ behavior: 'smooth', block: 'center' })}\",\n  \"onRowUnselected\": \"(row) => { row.rowElements.forEach(el => { if (el.style) { el.style['background-color'] = '' } });}\"   \n}",
  "description": "<h2>Hacker News Info</h2><p>Hackernews is a website that is popular among developers and entrepreneurs. Anybody can create an account and add content which is presented in a timeline format (most recent first).</p><image src='https://geoffreylitt.github.io/wildcard/examples/_images/hackernews/wildcard_open.png'></image>"
}

]

module.exports = cannedAdapters;